import React, { useEffect, useRef } from 'react';
import { Form, Checkbox, Input, Typography, Card, Radio, Space, Button, Select, Grid, Row, Col, InputNumber } from 'antd';
import LazyDatePicker from '../../../../components/lazy/LazyDatePicker';
import { PlusOutlined, MinusCircleOutlined } from '@ant-design/icons';
import type { FormInstance } from 'antd';

const { Title, Text } = Typography;
const { TextArea } = Input;
const { useBreakpoint } = Grid;

// 常见慢性疾病选项
const commonDiseases = [
  '高血压', '糖尿病', '冠心病', '脑卒中',
  '慢性阻塞性肺疾病(COPD)', 
  '哮喘', '肝炎', '结核', '肾脏疾病', '恶性肿瘤'
];

interface PastHistorySectionProps {
  form: FormInstance;
}

const PastHistorySection: React.FC<PastHistorySectionProps> = ({ form }) => {
  const screens = useBreakpoint();
  const isMobile = !screens.md;
  const EMPTY_ARR = React.useMemo<string[]>(() => [], []);
  type DiseaseDetail = { year?: number; control?: string; medication?: string };
  const EMPTY_OBJ = React.useMemo<Record<string, DiseaseDetail>>(() => ({}), []);
  const EMPTY_SURGERIES = React.useMemo<Record<string, unknown>[]>(() => [], []);
  const EMPTY_TRANSFUSIONS = React.useMemo<Record<string, unknown>[]>(() => [], []);
  const EMPTY_ALLERGIES = React.useMemo<Record<string, unknown>[]>(() => [], []);

  const selectedDiseases = Form.useWatch(['pastHistory', 'pmh_diseases'], form) || EMPTY_ARR;      
  const diseaseDetails: Record<string, DiseaseDetail> = Form.useWatch(['pastHistory', 'diseaseDetails'], form) || EMPTY_OBJ;
  const surgeries = (Form.useWatch(['pastHistory', 'surgeries'], form) as Record<string, unknown>[] | undefined) || EMPTY_SURGERIES;
  const transfusions = (Form.useWatch(['pastHistory', 'transfusions'], form) as Record<string, unknown>[] | undefined) || EMPTY_TRANSFUSIONS;
  const allergies = (Form.useWatch(['pastHistory', 'allergies'], form) as Record<string, unknown>[] | undefined) || EMPTY_ALLERGIES;
  const noDiseaseHistory = Form.useWatch(['pastHistory', 'noDiseaseHistory'], form);
  const noSurgeriesTrauma = Form.useWatch(['pastHistory', 'noSurgeriesTrauma'], form);
  const noTransfusions = Form.useWatch(['pastHistory', 'noTransfusions'], form);
  const noAllergies = Form.useWatch(['pastHistory', 'noAllergies'], form);

  // 标记用户是否手动修改过病史文本
  const userModifiedIllnessRef = useRef<boolean>(false);

  useEffect(() => {
    const curr = form.getFieldValue(['pastHistory', 'surgeries']);
    if (curr === undefined || curr === null) return;
    if (!Array.isArray(curr)) form.setFieldValue(['pastHistory', 'surgeries'], []);
  }, [form]);

  useEffect(() => {
    const curr = form.getFieldValue(['pastHistory', 'allergies']);
    if (curr === undefined || curr === null) return;
    if (!Array.isArray(curr)) form.setFieldValue(['pastHistory', 'allergies'], []);
  }, [form]);

  useEffect(() => {
    const curr = form.getFieldValue(['pastHistory', 'transfusions']);
    if (curr === undefined || curr === null) return;
    if (!Array.isArray(curr)) form.setFieldValue(['pastHistory', 'transfusions'], []);
  }, [form]);

  // 实时同步结构化数据到 illnessHistory 字符串字段
  useEffect(() => {
    const parts: string[] = [];

    // 1. 常见疾病
    if (selectedDiseases.length > 0) {
        const diseaseTexts = selectedDiseases.map((d: string) => {
            const details = diseaseDetails[d];
            let detailStr = '';
            if (details) {
                const info = [];
                if (details.year) info.push(`确诊${details.year}年`);
                if (details.control) info.push(`控制${details.control}`);
                if (details.medication) info.push(`用药：${details.medication}`);
                if (info.length > 0) detailStr = `（${info.join('，')}）`;
            }
            return `${d}${detailStr}`;
        });
        parts.push(`既往患有：${diseaseTexts.join('、')}。`);
    }

    // 传染病
    const infectious = form.getFieldValue(['pastHistory', 'infectiousHistory']);
    if (infectious) parts.push(`传染病史：${infectious}。`);

    const other = form.getFieldValue(['pastHistory', 'pmh_other']);
    if (other) parts.push(`其他疾病：${other}。`);

    const autoGenerated = parts.length > 0 ? parts.join('\n') : '';

    // 仅在相关字段变化且用户未手动修改时更新
    const currentText = form.getFieldValue(['pastHistory', 'illnessHistory']);
    if (!userModifiedIllnessRef.current && currentText !== autoGenerated) {
       form.setFieldValue(['pastHistory', 'illnessHistory'], autoGenerated);
    }
  }, [selectedDiseases, diseaseDetails, form]);

  useEffect(() => {
    if (selectedDiseases.length > 0 && noDiseaseHistory) {
      form.setFieldValue(['pastHistory', 'noDiseaseHistory'], false);
    }
  }, [form, noDiseaseHistory, selectedDiseases.length]);

  useEffect(() => {
    if (Array.isArray(surgeries) && surgeries.length > 0 && noSurgeriesTrauma) {
      form.setFieldValue(['pastHistory', 'noSurgeriesTrauma'], false);
    }
  }, [form, noSurgeriesTrauma, surgeries]);

  useEffect(() => {
    if (!noSurgeriesTrauma) return;
    const curr = form.getFieldValue(['pastHistory', 'surgeries']);
    if (Array.isArray(curr) && curr.length === 0) return;
    form.setFieldValue(['pastHistory', 'surgeries'], []);
  }, [form, noSurgeriesTrauma]);

  useEffect(() => {
    if (Array.isArray(transfusions) && transfusions.length > 0 && noTransfusions) {
      form.setFieldValue(['pastHistory', 'noTransfusions'], false);
    }
  }, [form, noTransfusions, transfusions]);

  useEffect(() => {
    if (!noTransfusions) return;
    const curr = form.getFieldValue(['pastHistory', 'transfusions']);
    if (Array.isArray(curr) && curr.length === 0) return;
    form.setFieldValue(['pastHistory', 'transfusions'], []);
  }, [form, noTransfusions]);

  useEffect(() => {
    if (Array.isArray(allergies) && allergies.length > 0 && noAllergies) {
      form.setFieldValue(['pastHistory', 'noAllergies'], false);
    }
  }, [allergies, form, noAllergies]);

  useEffect(() => {
    if (!noAllergies) return;
    const curr = form.getFieldValue(['pastHistory', 'allergies']);
    if (Array.isArray(curr) && curr.length === 0) return;
    form.setFieldValue(['pastHistory', 'allergies'], []);
  }, [form, noAllergies]);

  return (
    <div className="section-container">
      <Title level={4} style={{ marginBottom: 24 }}>既往史 (Past History)</Title>

      {/* 1. 一般健康状况 */}
      <Card type="inner" title="【既往一般健康状况】" size="small" style={{ marginBottom: 24 }}>   
        <Form.Item name={['pastHistory', 'generalHealth']} initialValue="good">
            <Radio.Group>
                <Radio value="good">良好</Radio>
                <Radio value="fair">一般</Radio>
                <Radio value="poor">较差</Radio>
            </Radio.Group>
        </Form.Item>
      </Card>

      {/* 2. 疾病史 */}
      <Card type="inner" title="【疾病史】" size="small" style={{ marginBottom: 24 }}>
         <Form.Item name={['pastHistory', 'pmh_diseases']} label="常见慢性病">
            <Checkbox.Group>
                <Row>
                    {commonDiseases.map(d => <Col xs={12} sm={8} md={8} key={d}><Checkbox value={d}>{d}</Checkbox></Col>)}
                </Row>
            </Checkbox.Group>
         </Form.Item>
         {selectedDiseases.length === 0 && (
           <Form.Item name={['pastHistory', 'noDiseaseHistory']} valuePropName="checked">
             <Checkbox>否认疾病史</Checkbox>
           </Form.Item>
         )}
         {/* 选中的疾病显示详情输入 */}
         {selectedDiseases.map((d: string) => (
             <div key={d} style={{ marginBottom: 12, background: '#f5f5f5', padding: 8, borderRadius: 4 }}>
                 <Text strong>{d}详情：</Text>
                 {isMobile ? (
                   <Row gutter={[8, 8]} style={{ marginTop: 8 }}>
                     <Col xs={24}>
                       <Form.Item name={['pastHistory', 'diseaseDetails', d, 'year']} style={{ marginBottom: 0 }}>
                         <InputNumber placeholder="确诊年份" style={{ width: '100%' }} />
                       </Form.Item>
                     </Col>
                     <Col xs={24}>
                       <Form.Item name={['pastHistory', 'diseaseDetails', d, 'control']} style={{ marginBottom: 0 }}>
                         <Input placeholder="控制情况" allowClear />
                       </Form.Item>
                     </Col>
                     <Col xs={24}>
                       <Form.Item name={['pastHistory', 'diseaseDetails', d, 'medication']} style={{ marginBottom: 0 }}>
                         <Input placeholder="用药情况" allowClear />
                       </Form.Item>
                     </Col>
                   </Row>
                 ) : (
                   <Space>
                       <Form.Item name={['pastHistory', 'diseaseDetails', d, 'year']} noStyle>     
                         <InputNumber placeholder="确诊年份" style={{ width: 120 }} />
                       </Form.Item>
                       <Form.Item name={['pastHistory', 'diseaseDetails', d, 'control']} noStyle>  
                         <Input placeholder="控制情况" style={{ width: 180 }} allowClear />        
                       </Form.Item>
                       <Form.Item name={['pastHistory', 'diseaseDetails', d, 'medication']} noStyle>
                         <Input placeholder="用药情况" style={{ width: 220 }} allowClear />        
                       </Form.Item>
                   </Space>
                 )}
             </div>
         ))}
         <Form.Item name={['pastHistory', 'infectiousHistory']} label="传染病史">
             <Input placeholder="如：肝炎、结核等（无则留空）" />
         </Form.Item>
         <Form.Item name={['pastHistory', 'illnessHistory']} label="疾病史综述">
             <TextArea rows={3} onChange={() => userModifiedIllnessRef.current = true} />
         </Form.Item>
      </Card>

      {/* 3. 手术外伤史 */}
      <Card type="inner" title="【手术外伤史】" size="small" style={{ marginBottom: 24 }}>
         <Form.Item name={['pastHistory', 'noSurgeriesTrauma']} valuePropName="checked">
           <Checkbox>否认手术外伤史</Checkbox>
         </Form.Item>
         <Form.List name={['pastHistory', 'surgeries']}>
           {(fields, { add, remove }) => (
             <>
               {!noSurgeriesTrauma && (
                 <>
                   {fields.map(({ key, name, ...restField }) => (
                     <Space
                       key={key}
                       style={{ display: 'flex', marginBottom: 8, width: '100%' }}
                       align={isMobile ? 'start' : 'baseline'}
                       orientation={isMobile ? 'vertical' : 'horizontal'}
                     >
                       <Form.Item
                         {...restField}
                         name={[name, 'date']}
                         style={isMobile ? { marginBottom: 0, width: '100%' } : { marginBottom: 0 }}
                       >
                         <LazyDatePicker
                           placeholder="时间"
                           picker="month"
                           style={isMobile ? { width: '100%' } : undefined}
                           placement="bottomLeft"
                           classNames={{ popup: { root: isMobile ? 'msia-mobile-picker' : undefined } }}
                           getPopupContainer={(trigger: HTMLElement) => (isMobile ? document.body : trigger.parentElement ?? document.body)}
                         />
                       </Form.Item>
                       <Form.Item
                         {...restField}
                         name={[name, 'location']}
                         style={isMobile ? { marginBottom: 0, width: '100%' } : { marginBottom: 0 }}
                       >
                         <Input placeholder="地点/医院" style={isMobile ? { width: '100%' } : undefined} />
                       </Form.Item>
                       <Form.Item
                         {...restField}
                         name={[name, 'name']}
                         rules={[{ required: true, message: '请输入手术/外伤名称' }]}
                         style={isMobile ? { marginBottom: 0, width: '100%' } : { marginBottom: 0 }}
                       >
                         <Input placeholder="手术/外伤名称" style={isMobile ? { width: '100%' } : undefined} />
                       </Form.Item>
                       <Form.Item
                         {...restField}
                         name={[name, 'outcome']}
                         style={isMobile ? { marginBottom: 0, width: '100%' } : { marginBottom: 0 }}
                       >
                         <Input placeholder="预后情况" style={isMobile ? { width: '100%' } : undefined} />
                       </Form.Item>
                       <MinusCircleOutlined onClick={() => remove(name)} />
                     </Space>
                   ))}
                   <Form.Item>
                     <Button
                       type="dashed"
                       onClick={() => {
                         const curr = form.getFieldValue(['pastHistory', 'surgeries']);
                         if (!Array.isArray(curr)) form.setFieldValue(['pastHistory', 'surgeries'], []);
                         add();
                       }}
                       block
                       icon={<PlusOutlined />}
                     >
                       添加手术/外伤记录
                     </Button>
                   </Form.Item>
                 </>
               )}
             </>
           )}
         </Form.List>
      </Card>

      {/* 4. 输血史 */}
      <Card type="inner" title="【输血史】" size="small" style={{ marginBottom: 24 }}>
         <Form.Item name={['pastHistory', 'noTransfusions']} valuePropName="checked">
           <Checkbox>否认输血史</Checkbox>
         </Form.Item>
         <Form.List name={['pastHistory', 'transfusions']}>
           {(fields, { add, remove }) => (
             <>
               {!noTransfusions && (
                 <>
                   {fields.map(({ key, name, ...restField }) => (
                     <Space
                       key={key}
                       style={{ display: 'flex', marginBottom: 8, width: '100%' }}
                       align={isMobile ? 'start' : 'baseline'}
                       orientation={isMobile ? 'vertical' : 'horizontal'}
                     >
                       <Form.Item
                         {...restField}
                         name={[name, 'date']}
                         style={isMobile ? { marginBottom: 0, width: '100%' } : { marginBottom: 0 }}
                       >
                         <LazyDatePicker
                           placeholder="输血时间"
                           style={isMobile ? { width: '100%' } : undefined}
                           placement="bottomLeft"
                           classNames={{ popup: { root: isMobile ? 'msia-mobile-picker' : undefined } }}
                           getPopupContainer={(trigger: HTMLElement) => (isMobile ? document.body : trigger.parentElement ?? document.body)}
                         />
                       </Form.Item>
                       <Form.Item
                         {...restField}
                         name={[name, 'reason']}
                         style={isMobile ? { marginBottom: 0, width: '100%' } : { marginBottom: 0 }}
                       >
                         <Input placeholder="原因" style={isMobile ? { width: '100%' } : undefined} />
                       </Form.Item>
                       <Form.Item
                         {...restField}
                         name={[name, 'amount']}
                         style={isMobile ? { marginBottom: 0, width: '100%' } : { marginBottom: 0 }}
                       >
                         <Input placeholder="量/成分" style={isMobile ? { width: '100%' } : undefined} />
                       </Form.Item>
                       <Form.Item
                         {...restField}
                         name={[name, 'reaction']}
                         style={isMobile ? { marginBottom: 0, width: '100%' } : { marginBottom: 0 }}
                       >
                         <Input placeholder="不良反应" style={isMobile ? { width: '100%' } : undefined} />
                       </Form.Item>
                       <MinusCircleOutlined onClick={() => remove(name)} />
                     </Space>
                   ))}
                   <Form.Item>
                     <Button
                       type="dashed"
                       onClick={() => {
                         const curr = form.getFieldValue(['pastHistory', 'transfusions']);
                         if (!Array.isArray(curr)) form.setFieldValue(['pastHistory', 'transfusions'], []);
                         add();
                       }}
                       block
                       icon={<PlusOutlined />}
                     >
                       添加输血记录
                     </Button>
                   </Form.Item>
                 </>
               )}
             </>
           )}
         </Form.List>
      </Card>

      {/* 5. 过敏史 */}
      <Card type="inner" title="【过敏史】" size="small" style={{ marginBottom: 24 }}>
        <Form.Item name={['pastHistory', 'noAllergies']} valuePropName="checked">
          <Checkbox>否认过敏史</Checkbox>
        </Form.Item>
        <Form.List name={['pastHistory', 'allergies']}>
           {(fields, { add, remove }) => (
             <>
               {!noAllergies && (
                 <>
                   {fields.map(({ key, name, ...restField }) => (
                     <Space key={key} style={{ display: 'flex', marginBottom: 8 }} align="baseline">
                       <Form.Item
                         {...restField}
                         name={[name, 'allergen']}
                         label="过敏原"
                         rules={[{ required: true, message: '请输入过敏原' }]}
                       >
                         <Input placeholder="药物/食物名称" />
                       </Form.Item>
                       <Form.Item
                         {...restField}
                         name={[name, 'reaction']}
                         label="反应"
                       >
                         <Input placeholder="过敏表现" />
                       </Form.Item>
                       <Form.Item
                         {...restField}
                         name={[name, 'severity']}
                         label="严重程度"
                       >
                          <Select placeholder="程度" style={{ width: 80 }}>
                            <Select.Option value="mild">轻度</Select.Option>
                            <Select.Option value="moderate">中度</Select.Option>
                            <Select.Option value="severe">重度</Select.Option>
                          </Select>
                       </Form.Item>
                       <MinusCircleOutlined onClick={() => remove(name)} />
                     </Space>
                   ))}
                   <Form.Item>
                     <Button
                       type="dashed"
                       onClick={() => {
                         const curr = form.getFieldValue(['pastHistory', 'allergies']);
                         if (!Array.isArray(curr)) form.setFieldValue(['pastHistory', 'allergies'], []);
                         add();
                       }}
                       block
                       icon={<PlusOutlined />}
                     >
                       添加过敏记录
                     </Button>
                   </Form.Item>
                 </>
               )}
             </>
           )}
         </Form.List>
      </Card>

      {/* 6. 预防接种史 */}
      <Card type="inner" title="【预防接种史】" size="small">
          <Form.Item name={['pastHistory', 'vaccinationHistory']} label="接种情况">
              <TextArea rows={2} placeholder="按计划接种/未接种/特殊接种史" />
          </Form.Item>
      </Card>
    </div>
  );
};

export default PastHistorySection;
