import React, { useEffect, useRef } from 'react';
import { Form, Input, Radio, Typography, Card, Row, Col, InputNumber, Statistic, Space } from 'antd';
import BirthplaceSelect from '../../../../components/BirthplaceSelect';

const { Title } = Typography;
const { TextArea } = Input;
import { theme } from 'antd';

const PersonalHistorySection: React.FC = () => {
  const form = Form.useFormInstance();
  const { token } = theme.useToken();
  
  // 监听吸烟相关字段
  const smokingStatus = Form.useWatch(['personalHistory', 'smoking_status'], form);
  const cigarettesPerDay = Form.useWatch(['personalHistory', 'cigarettesPerDay'], form);
  const smokingYears = Form.useWatch(['personalHistory', 'smokingYears'], form);
  const smokingHistory = Form.useWatch(['personalHistory', 'smokingHistory'], form);
  
  // 监听饮酒相关字段
  const alcoholStatus = Form.useWatch(['personalHistory', 'alcohol_status'], form);
  const drinkVolume = Form.useWatch(['personalHistory', 'drinkVolume'], form); // ml
  const alcoholDegree = Form.useWatch(['personalHistory', 'alcoholDegree'], form); // %
  const drinkFreqPerWeek = Form.useWatch(['personalHistory', 'drinkFreqPerWeek'], form); // 次/周
  const drinkingHistory = Form.useWatch(['personalHistory', 'drinkingHistory'], form);
  
  // 监听需要反向同步到一般项目的字段
  const personalOccupation = Form.useWatch(['personalHistory', 'occupation'], form);
  const personalEmployer = Form.useWatch(['personalHistory', 'employer'], form);
  const personalBirthplace = Form.useWatch(['personalHistory', 'birthplace'], form);
  
  // 标记用户是否手动修改过吸烟/饮酒史文本
  const userModifiedSmokingRef = useRef<boolean>(false);
  const userModifiedDrinkingRef = useRef<boolean>(false);
  // 记录上一次结构化数据
  const lastSmokingDataRef = useRef<{ status?: string; cigarettes?: number; years?: number }>({});
  const lastDrinkingDataRef = useRef<{ status?: string; volume?: number; degree?: number; freq?: number }>({});

  /**
   * 双向同步：职业（个人史 -> 一般项目）
   */
  useEffect(() => {
    const generalOccupation = form.getFieldValue('occupation');
    if (personalOccupation && personalOccupation !== generalOccupation) {
      form.setFieldValue('occupation', personalOccupation);
    }
  }, [personalOccupation, form]);

  /**
   * 双向同步：工作单位（个人史 -> 一般项目）
   */
  useEffect(() => {
    const generalEmployer = form.getFieldValue('employer');
    if (personalEmployer && personalEmployer !== generalEmployer) {
      form.setFieldValue('employer', personalEmployer);
    }
  }, [personalEmployer, form]);

  /**
   * 双向同步：出生地（个人史 -> 一般项目）
   */
  useEffect(() => {
    const generalPlaceOfBirth = form.getFieldValue('placeOfBirth');
    if (personalBirthplace && personalBirthplace !== generalPlaceOfBirth) {
      form.setFieldValue('placeOfBirth', personalBirthplace);
    }
  }, [personalBirthplace, form]);

  // 监听吸烟史文本变化，检测用户手动修改
  useEffect(() => {
    if (!smokingHistory) return;
    
    let autoGenerated = smokingStatus;
    if ((smokingStatus === '吸烟' || smokingStatus === '已戒烟') && cigarettesPerDay && smokingYears) {
        const index = cigarettesPerDay * smokingYears;
        autoGenerated += `，${cigarettesPerDay}支/日 × ${smokingYears}年，吸烟指数 ${index}。`;
        if (smokingStatus === '已戒烟') {
            const quitYears = form.getFieldValue(['personalHistory', 'quitSmokingYears']);
            if (quitYears) autoGenerated += `已戒烟${quitYears}年。`;
        }
    } else if (smokingStatus === '从不') {
        autoGenerated = '从不吸烟。';
    }
    
    if (smokingHistory !== autoGenerated) {
      userModifiedSmokingRef.current = true;
    }
  }, [smokingHistory, smokingStatus, cigarettesPerDay, smokingYears, form]);

  // 监听饮酒史文本变化，检测用户手动修改
  useEffect(() => {
    if (!drinkingHistory) return;
    
    let autoGenerated = alcoholStatus;
    if ((alcoholStatus === '饮酒' || alcoholStatus === '已戒酒') && drinkVolume && alcoholDegree) {
        const gramsNum = (drinkVolume * (alcoholDegree / 100) * 0.8);
        const grams = gramsNum.toFixed(1);
        const weekly = typeof drinkFreqPerWeek === 'number' && drinkFreqPerWeek > 0 ? (gramsNum * drinkFreqPerWeek).toFixed(1) : undefined;
        autoGenerated += `，每次约 ${drinkVolume}ml (${alcoholDegree}%)，折合酒精量 ${grams}g${weekly ? `；每周约 ${weekly}g` : ''}。`;
        if (alcoholStatus === '已戒酒') {
            const quitYears = form.getFieldValue(['personalHistory', 'quitDrinkingYears']);
            if (quitYears) autoGenerated += `已戒酒${quitYears}年。`;
        }
    } else if (alcoholStatus === '从不') {
        autoGenerated = '从不饮酒。';
    }
    
    if (drinkingHistory !== autoGenerated) {
      userModifiedDrinkingRef.current = true;
    }
  }, [drinkingHistory, alcoholStatus, drinkVolume, alcoholDegree, drinkFreqPerWeek, form]);
  
  /**
   * 自动计算吸烟指数并同步到 smokingHistory（仅在值变化时写入）
   */
  useEffect(() => {
    // 检查吸烟相关字段是否变化
    const currentSmokingData = { status: smokingStatus, cigarettes: cigarettesPerDay, years: smokingYears };
    const smokingChanged = JSON.stringify(currentSmokingData) !== JSON.stringify(lastSmokingDataRef.current);
    lastSmokingDataRef.current = currentSmokingData;
    
    let result = smokingStatus;
    let index = 0;
    
    if ((smokingStatus === '吸烟' || smokingStatus === '已戒烟') && cigarettesPerDay && smokingYears) {
        index = cigarettesPerDay * smokingYears;
        result += `，${cigarettesPerDay}支/日 × ${smokingYears}年，吸烟指数 ${index}。`;
        if (smokingStatus === '已戒烟') {
            const quitYears = form.getFieldValue(['personalHistory', 'quitSmokingYears']);
            if (quitYears) result += `已戒烟${quitYears}年。`;
        }
    } else if (smokingStatus === '从不') {
        result = '从不吸烟。';
    }
    
    if (result) {
        const prevText = form.getFieldValue(['personalHistory', 'smokingHistory']);
        const prevIndex = form.getFieldValue(['personalHistory', 'smokingIndex']);
        // 只在吸烟字段变化且用户未手动修改时，才自动更新
        if (smokingChanged && !userModifiedSmokingRef.current && (!prevText || prevText === '')) {
          form.setFieldValue(['personalHistory', 'smokingHistory'], result);
        }
        if (prevIndex !== index) {
          form.setFieldValue(['personalHistory', 'smokingIndex'], index);
        }
    }
  }, [smokingStatus, cigarettesPerDay, smokingYears, form]);

  /**
   * 自动计算饮酒量与每周总量并同步到 drinkingHistory/weeklyAlcoholGrams（仅在值变化时写入）
   */
  useEffect(() => {
    // 检查饮酒相关字段是否变化
    const currentDrinkingData = { status: alcoholStatus, volume: drinkVolume, degree: alcoholDegree, freq: drinkFreqPerWeek };
    const drinkingChanged = JSON.stringify(currentDrinkingData) !== JSON.stringify(lastDrinkingDataRef.current);
    lastDrinkingDataRef.current = currentDrinkingData;
    
    let result = alcoholStatus;
    
    if ((alcoholStatus === '饮酒' || alcoholStatus === '已戒酒') && drinkVolume && alcoholDegree) {
        const gramsNum = (drinkVolume * (alcoholDegree / 100) * 0.8);
        const grams = gramsNum.toFixed(1);
        const weekly = typeof drinkFreqPerWeek === 'number' && drinkFreqPerWeek > 0 ? (gramsNum * drinkFreqPerWeek).toFixed(1) : undefined;
        result += `，每次约 ${drinkVolume}ml (${alcoholDegree}%)，折合酒精量 ${grams}g${weekly ? `；每周约 ${weekly}g` : ''}。`;
        if (alcoholStatus === '已戒酒') {
            const quitYears = form.getFieldValue(['personalHistory', 'quitDrinkingYears']);
            if (quitYears) result += `已戒酒${quitYears}年。`;
        }
    } else if (alcoholStatus === '从不') {
        result = '从不饮酒。';
    }
    
    if (result) {
        // 只在饮酒字段变化且用户未手动修改时，才自动更新
        if (drinkingChanged && !userModifiedDrinkingRef.current) {
          form.setFieldValue(['personalHistory', 'drinkingHistory'], result);
        }
        // 存储每次与每周的估算负荷，便于助手面板提示
        const gramsNum = (drinkVolume && alcoholDegree) ? (drinkVolume * (alcoholDegree / 100) * 0.8) : 0;
        const weekly = typeof drinkFreqPerWeek === 'number' && drinkFreqPerWeek > 0 ? (gramsNum * drinkFreqPerWeek) : 0;
        const weeklyVal = Number.isFinite(weekly) ? Number(weekly.toFixed(1)) : 0;
        const prevWeekly = form.getFieldValue(['personalHistory', 'weeklyAlcoholGrams']);
        if (prevWeekly !== weeklyVal) {
          form.setFieldValue(['personalHistory', 'weeklyAlcoholGrams'], weeklyVal);
        }
    }
  }, [alcoholStatus, drinkVolume, alcoholDegree, drinkFreqPerWeek, form]);

  return (
    <div className="section-container">
      <Title level={4} style={{ 
        marginBottom: 24, 
        fontWeight: 600,
        color: 'var(--msia-text-primary)',
        letterSpacing: 0.5,
        paddingBottom: 12,
        borderBottom: '2px solid var(--msia-primary)',
        display: 'inline-block',
      }}>个人史 <span style={{ fontSize: 14, fontWeight: 400, color: 'var(--msia-text-tertiary)', marginLeft: 8 }}>Personal History</span></Title>
      
      {/* 隐藏字段，存储最终生成的字符段 */}
      <Form.Item name={['personalHistory', 'smokingHistory']} hidden><Input /></Form.Item>
      <Form.Item name={['personalHistory', 'drinkingHistory']} hidden><Input /></Form.Item>
      
      <Card type="inner" title="1. 社会经历与职业" size="small" style={{ marginBottom: 24 }}>
        <Row gutter={[12, 12]}>
            <Col xs={24} sm={12} md={12}>
                <Form.Item
                  name={['personalHistory', 'birthplace']}
                  label="出生地"
                  rules={[{ required: true, message: '请选择出生地' }]}
                >
                    <BirthplaceSelect placeholder="选择出生地（到区县级）" />
                </Form.Item>
            </Col>
            <Col xs={24} sm={12} md={12}>
                <Form.Item
                  name={['personalHistory', 'residence']}
                  label="居留地"
                  rules={[{ required: true, message: '请选择居留地' }]}
                >
                    <BirthplaceSelect placeholder="选择长期居住地（到区县级）" />
                </Form.Item>
            </Col>
        </Row>
        <Form.Item name={['personalHistory', 'epidemic_contact']} label="疫区接触史">
            <TextArea rows={2} placeholder="近期是否去过传染病流行区，接触过确诊患者等" />
        </Form.Item>
        <Row gutter={24}>
            <Col span={12}>
                <Form.Item name="occupation" label="职业">
                    <Input placeholder="患者职业" />
                </Form.Item>
            </Col>
            <Col span={12}>
                <Form.Item name="employer" label="工作单位">
                    <Input placeholder="工作单位" />
                </Form.Item>
            </Col>
        </Row>
        <Form.Item name={['personalHistory', 'social']} label="教育/其他社会经历">
            <TextArea rows={2} placeholder="受教育程度、居住地变迁等" />
        </Form.Item>
        <Form.Item name={['personalHistory', 'work_cond']} label="工作环境/接触史">
            <TextArea rows={2} placeholder="粉尘、毒物、放射性物质接触史等" />
        </Form.Item>
      </Card>

      <Card type="inner" title="2. 习惯与嗜好（自动计算）" size="small" style={{ marginBottom: 24 }}>
          {/* 吸烟史计算器 */}
          <div style={{ 
            background: token.colorFillAlter, 
            padding: 16, 
            borderRadius: 8, 
            marginBottom: 16, 
            border: `1px solid ${token.colorBorderSecondary}` 
          }}>
            <Row gutter={[12, 12]} align="top">
                <Col xs={24} sm={24} md={6}>
                    <Form.Item
                      name={['personalHistory', 'smoking_status']}
                      label="吸烟状态"
                      initialValue="从不"
                      style={{ marginBottom: 0 }}
                      rules={[{ required: true, message: '请选择吸烟状态' }]}
                    >
                        <Radio.Group buttonStyle="solid" style={{ width: '100%', display: 'flex' }}>
                            <Radio.Button value="从不" style={{ flex: 1, textAlign: 'center' }}>从不</Radio.Button>
                            <Radio.Button value="已戒烟" style={{ flex: 1, textAlign: 'center' }}>戒烟</Radio.Button>
                            <Radio.Button value="吸烟" style={{ flex: 1, textAlign: 'center' }}>吸烟</Radio.Button>
                        </Radio.Group>
                    </Form.Item>
                </Col>
                
                {(smokingStatus === '吸烟' || smokingStatus === '已戒烟') && (
                    <>
                        <Col xs={12} sm={12} md={6}>
                            <Form.Item 
                                name={['personalHistory', 'cigarettesPerDay']} 
                                label="每日吸烟(支/日)" 
                                style={{ marginBottom: 0 }}
                                rules={[
                                    { required: true, message: '请输入每日吸烟支数' },
                                    { type: 'number', min: 1, max: 100, message: '请输入1-100之间的数字' }
                                ]}
                            >
                                <InputNumber style={{ width: '100%' }} min={1} max={100} placeholder="1-100" />
                            </Form.Item>
                        </Col>
                        <Col xs={12} sm={12} md={6}>
                            <Form.Item 
                                name={['personalHistory', 'smokingYears']} 
                                label="烟龄(年)" 
                                style={{ marginBottom: 0 }}
                                rules={[
                                    { required: true, message: '请输入烟龄' },
                                    { type: 'number', min: 1, max: 80, message: '请输入1-80之间的数字' }
                                ]}
                            >
                                <InputNumber style={{ width: '100%' }} min={1} max={80} placeholder="1-80" />
                            </Form.Item>
                        </Col>
                        <Col xs={24} sm={24} md={6}>
                             <Statistic 
                                title="吸烟指数" 
                                value={form.getFieldValue(['personalHistory', 'smokingIndex']) || 0} 
                                suffix="年支" 
                                styles={{ content: { fontSize: 16, color: '#fa8c16' } }}
                             />
                        </Col>
                        {smokingStatus === '已戒烟' && (
                             <Col span={24} style={{ marginTop: 12 }}>
                                 <Form.Item 
                                    name={['personalHistory', 'quitSmokingYears']} 
                                    label="已戒烟年数"
                                    rules={[
                                        { type: 'number', min: 1, max: 80, message: '请输入1-80之间的数字' }
                                    ]}
                                 >
                                     <Space.Compact>
                                       <InputNumber style={{ width: '100%' }} min={1} max={80} placeholder="1-80" />
                                       <span style={{ display: 'inline-flex', alignItems: 'center', padding: '0 8px', background: token.colorFillAlter, border: `1px solid ${token.colorBorder}`, borderLeft: 'none', borderRadius: '0 6px 6px 0', color: token.colorText }}>年</span>
                                     </Space.Compact>
                                 </Form.Item>
                             </Col>
                        )}
                    </>
                )}
            </Row>
          </div>

          {/* 饮酒史计算器 */}
          <div style={{ 
            background: token.colorInfoBg, 
            padding: 16, 
            borderRadius: 8, 
            marginBottom: 16, 
            border: `1px solid ${token.colorInfoBorder}` 
          }}>
            <Row gutter={[12, 12]} align="top">
                <Col xs={24} sm={24} md={6}>
                    <Form.Item
                      name={['personalHistory', 'alcohol_status']}
                      label="饮酒状态"
                      initialValue="从不"
                      style={{ marginBottom: 0 }}
                      rules={[{ required: true, message: '请选择饮酒状态' }]}
                    >
                        <Radio.Group buttonStyle="solid" style={{ width: '100%', display: 'flex' }}>
                            <Radio.Button value="从不" style={{ flex: 1, textAlign: 'center' }}>从不</Radio.Button>
                            <Radio.Button value="已戒酒" style={{ flex: 1, textAlign: 'center' }}>戒酒</Radio.Button>
                            <Radio.Button value="饮酒" style={{ flex: 1, textAlign: 'center' }}>饮酒</Radio.Button>
                        </Radio.Group>
                    </Form.Item>
                </Col>
                
                {(alcoholStatus === '饮酒' || alcoholStatus === '已戒酒') && (
                    <>
                        <Col xs={12} sm={12} md={6}>
                            <Form.Item 
                                name={['personalHistory', 'drinkVolume']} 
                                label="日饮量(ml)" 
                                style={{ marginBottom: 0 }}
                                rules={[
                                    { required: true, message: '请输入日饮量' },
                                    { type: 'number', min: 1, max: 2000, message: '请输入1-2000之间的数字' }
                                ]}
                            >
                                <InputNumber style={{ width: '100%' }} min={1} max={2000} step={50} placeholder="1-2000" />
                            </Form.Item>
                        </Col>
                        <Col xs={12} sm={12} md={6}>
                            <Form.Item 
                                name={['personalHistory', 'alcoholDegree']} 
                                label="度数(%)" 
                                style={{ marginBottom: 0 }}
                                rules={[
                                    { required: true, message: '请输入酒精度数' },
                                    { type: 'number', min: 1, max: 75, message: '请输入1-75之间的数字' }
                                ]}
                            >
                                <InputNumber style={{ width: '100%' }} min={1} max={75} placeholder="1-75" />
                            </Form.Item>
                        </Col>
                        <Col xs={24} sm={12} md={6}>
                            <Form.Item 
                                name={['personalHistory', 'drinkFreqPerWeek']} 
                                label="频率(次/周)" 
                                style={{ marginBottom: 0 }}
                                rules={[
                                    { type: 'number', min: 1, max: 7, message: '请输入1-7之间的数字' }
                                ]}
                            >
                                <InputNumber style={{ width: '100%' }} min={1} max={7} placeholder="1-7" />
                            </Form.Item>
                        </Col>
                        <Col span={24} style={{ marginTop: 12 }}>
                            <Statistic 
                                title="每周估算酒精量" 
                                value={form.getFieldValue(['personalHistory', 'weeklyAlcoholGrams']) || 0} 
                                suffix="g" 
                                styles={{ content: { fontSize: 16, color: '#2f54eb' } }}
                            />
                        </Col>
                         {alcoholStatus === '已戒酒' && (
                             <Col span={24} style={{ marginTop: 12 }}>
                                 <Form.Item name={['personalHistory', 'quitDrinkingYears']} label="已戒酒年数">
                                     <Space.Compact>
                                       <InputNumber style={{ width: '100%' }} min={0} />
                                       <span style={{ display: 'inline-flex', alignItems: 'center', padding: '0 8px', background: token.colorFillAlter, border: `1px solid ${token.colorBorder}`, borderLeft: 'none', borderRadius: '0 6px 6px 0', color: token.colorText }}>年</span>
                                     </Space.Compact>
                                 </Form.Item>
                             </Col>
                        )}
                    </>
                )}
            </Row>
          </div>

          <Form.Item name={['personalHistory', 'living_habits']} label="起居饮食">
              <Input placeholder="饮食习惯（如喜咸/喜烫）、睡眠情况等" />
          </Form.Item>

          <Form.Item name={['personalHistory', 'substances']} label="其他嗜好">
              <Input placeholder="药物依赖、其他不良嗜好" />
          </Form.Item>
      </Card>
      
      <Card type="inner" title="3. 性行为史" size="small">
          <Form.Item name={['personalHistory', 'sexual_history']} label="性行为史">
              <TextArea placeholder="如有不洁性交史等，请记录" />
          </Form.Item>
      </Card>
    </div>
  );
};

export default PersonalHistorySection;
