export const SYMPTOM_SYNONYMS: Record<string, string> = {
  "恶心与呕吐": "恶心呕吐",
  "呕吐伴恶心": "恶心呕吐",
  "恶心后呕吐": "恶心呕吐",
  "发烧": "发热",
  "体温升高": "发热",
  "高热": "发热",
  "眩晕": "眩晕",
  "头晕": "眩晕",
  "天旋地转": "眩晕",
  "痰中带血": "咯血",
  "吐血": "上消化道出血",
  "呕血": "上消化道出血",
  "黑色大便": "上消化道出血",
  "黑便": "上消化道出血",
  "柏油样便": "上消化道出血",
  "偏头痛": "头痛",
  "神经性头痛": "头痛"
};

export const SYMPTOM_NAME_TO_KEY: Record<string, string> = {
  "腹痛": "abdominal_pain",
  "发热": "fever",
  "头痛": "headache",
  "腹泻": "diarrhea",
  "胸痛": "chest_pain",
  "咳嗽": "cough_and_expectoration",
  "呼吸困难": "dyspnea",
  "咯血": "hemoptysis",
  "恶心呕吐": "nausea_vomiting",
  "上消化道出血": "hematemesis",
  "眩晕": "vertigo",
  "心悸": "palpitation",
  "乏力": "fatigue",
  "意识障碍": "disturbance_of_consciousness",
  "晕厥": "syncope",
  "抽搐": "tic_convulsion",
  "水肿": "edema",
  "黄疸": "jaundice",
  "关节痛": "arthralgia",
  "腰背痛": "lumbodorsalgia",
  "尿频尿急尿痛": "urinary_frequency_urgency_dysuria",
  "血尿": "hematuria",
  "便秘": "constipation",
  "体重下降": "emaciation",
  "黑便": "melena"
};
